### PR TITLE
fix win32 issues

### PR DESCRIPTION
**Pull request by jantimon**
Fixes a bug which breaks postinstallDev on windows.

Tested on Mac & Windows

### CODE REVIEW

**Comment by sachinraja** [comment]
I thought cross-spawn was supposed to solve these issues. I think we should just read the command from the package.json and execute it with `@yarnpkg/shell`.

**Comment by jantimon** [comment]
alright I'll take a look :)

**Comment by jantimon** [comment]
Cool idea - seems to work fine for windows and unix 👍

**Comment by sachinraja** [comment]
fixed in https://github.com/sachinraja/yarn-plugin-postinstall-dev/commit/070c4e38dea0d1eb40d00d93db638172bb8f4e6b. It uses the same method used here with `@yarnpkg/shell` (thanks for that implementation) and reads the command directly from your package.json.

Edit: switched to different method that mirrors the one used for `yarn run`

**Pull request closed without merging**
